services:
  app:
    build: .
    container_name: vatansoft-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=vatansoft
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - JWT_SECRET=supersecretkey
      - PORT=8080
    volumes:
      - .:/app  # 👈 Mounts your project directory into the container
    command: go run ./cmd/main.go  # 🟢 Rebuilds on each up

  db:
    image: postgres:17
    container_name: vatansoft-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vatansoft
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: vatansoft-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
